# NBA api webscraping - Teams Box Scores

In [1]:
import requests
import pandas as pd

In [2]:
games_url = 'https://stats.nba.com/stats/leaguegamelog?Counter=1000&DateFrom=&DateTo=&Direction=DESC&LeagueID=00&PlayerOrTeam=T&Season=2021-22&SeasonType=Regular+Season&Sorter=DATE'

In [3]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

In [4]:
response = requests.get(url=games_url, headers=headers).json()

In [5]:
games_info = response['resultSets'][0]['rowSet']

In [6]:
games_info[:1]

[['22021',
  1610612750,
  'MIN',
  'Minnesota Timberwolves',
  '0022101058',
  '2022-03-19',
  'MIN vs. MIL',
  'W',
  240,
  47,
  92,
  0.511,
  22,
  47,
  0.468,
  22,
  26,
  0.846,
  8,
  36,
  44,
  30,
  12,
  2,
  11,
  19,
  138,
  19,
  1]]

In [7]:
columns_list = [
    "SEASON_ID",
    "TEAM_ID",
    "TEAM_ABBREVIATION",
    "TEAM_NAME",
    "GAME_ID",
    "GAME_DATE",
    "MATCHUP",
    "WL",
    "MIN",
    "FGM",
    "FGA",
    "FG_PCT",
    "FG3M",
    "FG3A",
    "FG3_PCT",
    "FTM",
    "FTA",
    "FT_PCT",
    "OREB",
    "DREB",
    "REB",
    "AST",
    "STL",
    "BLK",
    "TOV",
    "PF",
    "PTS",
    "PLUS_MINUS",
    "VIDEO_AVAILABLE"
]

In [8]:
nba_game_detail_df = pd.DataFrame(games_info, columns=columns_list)

In [10]:
nba_game_detail_df.head(10)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22021,1610612750,MIN,Minnesota Timberwolves,0022101058,2022-03-19,MIN vs. MIL,W,240,47,...,36,44,30,12,2,11,19,138,19,1
1,22021,1610612749,MIL,Milwaukee Bucks,0022101058,2022-03-19,MIL @ MIN,L,240,43,...,37,51,27,6,4,14,18,119,-19,1
2,22021,1610612764,WAS,Washington Wizards,0022101061,2022-03-19,WAS vs. LAL,W,240,44,...,29,36,30,10,1,8,13,127,8,1
3,22021,1610612747,LAL,Los Angeles Lakers,0022101061,2022-03-19,LAL @ WAS,L,240,48,...,32,41,25,3,1,15,23,119,-8,1
4,22021,1610612765,DET,Detroit Pistons,0022101060,2022-03-19,DET @ CLE,L,240,41,...,28,38,23,10,6,16,22,109,-4,1
5,22021,1610612739,CLE,Cleveland Cavaliers,0022101060,2022-03-19,CLE vs. DET,W,240,45,...,32,45,28,7,4,16,16,113,4,1
6,22021,1610612742,DAL,Dallas Mavericks,0022101059,2022-03-19,DAL @ CHA,L,240,39,...,32,44,18,4,4,15,26,108,-21,1
7,22021,1610612766,CHA,Charlotte Hornets,0022101059,2022-03-19,CHA vs. DAL,W,240,44,...,36,46,33,8,8,9,18,129,21,1
8,22021,1610612756,PHX,Phoenix Suns,0022101056,2022-03-18,PHX vs. CHI,W,240,47,...,39,49,23,5,4,13,20,129,27,1
9,22021,1610612741,CHI,Chicago Bulls,0022101056,2022-03-18,CHI @ PHX,L,240,35,...,24,37,20,6,0,11,18,102,-27,1

In [12]:
nba_game_detail_df.to_csv('data/nba_game_details_2021-22.csv', index=False)